kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: exec
name: care-0.1 # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: package # 流水线名称
    commands: # 定义在Docker容器中执行的shell命令
      - echo hello world
      - cat /etc/profile
      - ls