kind: pipeline
type: exec
name: deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: greeting
    commands:
    - echo hello world
    - drone exec java -version
    when:
      branch:
        - main