kind: pipeline
type: exec
name: deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: maven:3-jdk-10
    commands:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      #- bash ./build.sh
    when:
      branch:
        - main