kind: pipeline
type: exec
name: deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: print a shit
    commands:
      - echo start build images...
      - echo wo anzhuangle git
      - sh ./build.sh
    when:
      branch:
        - master