kind: pipeline
type: exec
name: deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: print a shit
    commands:
      - echo start build images...
      - echo wo anzhuangle git
#      - export MAJOR_VERSION=1.0.rtm.
#      - export BUILD_NUMBER=$DRONE_BUILD_NUMBER
#      - export WORKSPACE=`pwd`
#      - bash ./build.sh
    when:
      branch:
        - master